### ISSUE TITLE
Change my portfolio contents

### ISSUE THREAD

**Issue by ierdss** [AndreiSager/andrei-portfolio#12]
# Tasks

- [ ] Cleanup introduction on what value I can bring to the company on the hero section. 
- [ ] Cleanup the about me section. Set the title of something about myself with 2 paragraphs and 4 sentences each.
- [ ] Revise the GUI to have a classy presentation.
- [ ] Grab the attention of employers using the power of animations.``
- [ ] Add reusable modals
- [ ] Add animations that fit
- [ ] Change about me content to a more professional tone
